module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v1.5-18-g7191b3c"

gitRepo : String 
gitRepo = "https://github.com/kgashok/qnaElm"

