module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v1.0-17-g70bb154"

gitRepo : String 
gitRepo = "https://github.com/kgashok/qnaElm"

