module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v1.5-11-g8fac56d"

gitRepo : String 
gitRepo = "https://github.com/kgashok/qnaElm"

